runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

libraries:
- name: webapp2
  version: latest

- name: MySQLdb
  version: "latest"

- name: django
  version: "1.2"

- name: pycrypto
  version: "2.6"

- name: lxml
  version: latest

- name: endpoints
  version: 1.0

- name: jinja2
  version: latest

- name: ssl
  version: latest

- name: numpy
  version: latest

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /att_case_hacks/static/
  static_dir: ATTCaseHacks/static

- url: /att_case_hacks/.*|^/att_case_hacks$
  script: ATTCaseHacks.app

- url: /_ah/admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: .*
  script: main.app


